-- supabase/migrations/0002_seed_questions.sql

TRUNCATE TABLE filler_questions;

INSERT INTO filler_questions (topic, summary, text, type, options, correct_answer, explanation) VALUES
('history', 'Ancient Egypt', 'Which pharaoh''s tomb was discovered intact in 1922?', 'multiple_choice', '["Ramses II", "Tutankhamun", "Akhenaten", "Seti I"]', 'Tutankhamun', 'Howard Carter discovered Tutankhamun''s tomb in the Valley of the Kings.'),
('history', 'Roman Empire', 'Who was the first Emperor of Rome?', 'multiple_choice', '["Julius Caesar", "Augustus", "Nero", "Tiberius"]', 'Augustus', 'Augustus became the first emperor after the defeat of Mark Antony.'),
('history', 'French Revolution', 'In what year did the French Revolution begin?', 'text', NULL, '1789', 'The revolution began with the storming of the Bastille.'),
('history', 'World War II', 'The D-Day landings took place in Normandy.', 'boolean', NULL, 'True', 'Operation Overlord began on June 6, 1944.'),
('history', 'Cold War', 'The Berlin Wall fell in what year?', 'text', NULL, '1989', 'The fall of the wall symbolized the end of the Cold War.'),
('history', 'Magna Carta', 'In which year was the Magna Carta signed?', 'multiple_choice', '["1066", "1215", "1492", "1588"]', '1215', 'King John signed the charter at Runnymede.'),
('history', 'Viking Age', 'Leif Erikson reached North America before Columbus.', 'boolean', NULL, 'True', 'Norse explorers reached Newfoundland around the year 1000.'),
('history', 'Industrial Revolution', 'Who invented the modern steam engine?', 'multiple_choice', '["James Watt", "Thomas Edison", "Eli Whitney", "Robert Fulton"]', 'James Watt', 'Watt''s engine was fundamental to the Industrial Revolution.'),
('history', 'Aztec Empire', 'What was the capital of the Aztec Empire?', 'text', NULL, 'Tenochtitlan', 'Tenochtitlan was built on an island in Lake Texcoco.'),
('history', 'American Civil War', 'The Emancipation Proclamation was issued by Abraham Lincoln.', 'boolean', NULL, 'True', 'Lincoln issued the order in 1863.'),
('science', 'Space', 'Which planet is known as the Red Planet?', 'multiple_choice', '["Venus", "Mars", "Jupiter", "Saturn"]', 'Mars', 'Mars appears red due to iron oxide on its surface.'),
('science', 'Biology', 'What is the powerhouse of the cell?', 'multiple_choice', '["Nucleus", "Ribosome", "Mitochondria", "Golgi Body"]', 'Mitochondria', 'Mitochondria generate most of the cell''s ATP.'),
('science', 'Physics', 'The speed of light is constant in a vacuum.', 'boolean', NULL, 'True', 'Light travels at approximately 299,792,458 meters per second.'),
('science', 'Chemistry', 'What is the chemical symbol for Gold?', 'text', NULL, 'Au', 'Au comes from the Latin word "aurum".'),
('science', 'Astronomy', 'What is the largest planet in our solar system?', 'text', NULL, 'Jupiter', 'Jupiter is a gas giant with massive gravity.'),
('science', 'Geology', 'What type of rock is formed from cooled magma?', 'multiple_choice', '["Sedimentary", "Metamorphic", "Igneous", "Quartz"]', 'Igneous', 'Magma cooling results in igneous formations.'),
('science', 'Human Body', 'How many bones are in the adult human body?', 'text', NULL, '206', 'Infants have more bones, which fuse as they grow.'),
('science', 'Mathematics', 'What is the square root of 144?', 'text', NULL, '12', '12 multiplied by 12 equals 144.'),
('science', 'Botany', 'Photosynthesis converts sunlight into energy.', 'boolean', NULL, 'True', 'Plants use chlorophyll to capture light energy.'),
('science', 'Evolution', 'Who wrote "On the Origin of Species"?', 'text', NULL, 'Charles Darwin', 'Darwin introduced the theory of natural selection.'),
('pop-culture', 'Movies', 'Which movie won the first Best Picture Oscar?', 'multiple_choice', '["Wings", "Sunrise", "The Jazz Singer", "Metropolis"]', 'Wings', 'Wings is a 1927 silent film.'),
('pop-culture', 'Music', 'Who is known as the King of Pop?', 'text', NULL, 'Michael Jackson', 'Jackson is one of the best-selling artists of all time.'),
('pop-culture', 'TV Shows', '"Friends" had 10 seasons.', 'boolean', NULL, 'True', 'The show ran from 1994 to 2004.'),
('pop-culture', 'Gaming', 'What is the best-selling video game of all time?', 'multiple_choice', '["Tetris", "Minecraft", "GTA V", "Wii Sports"]', 'Minecraft', 'Minecraft has sold over 300 million copies.'),
('pop-culture', 'Comics', 'What is Batman''s real name?', 'text', NULL, 'Bruce Wayne', 'Wayne became Batman after his parents'' murder.'),
('pop-culture', 'Streaming', 'Eleven is a character in "Stranger Things".', 'boolean', NULL, 'True', 'The character is played by Millie Bobby Brown.'),
('pop-culture', 'Animation', 'What was the first feature-length animated film?', 'multiple_choice', '["Pinocchio", "Snow White", "Dumbo", "Bambi"]', 'Snow White', 'Released by Disney in 1937.'),
('pop-culture', 'Internet', 'YouTube was founded in 2005.', 'boolean', NULL, 'True', 'It was founded by three former PayPal employees.'),
('pop-culture', 'Harry Potter', 'What is Harry Potter''s owl''s name?', 'text', NULL, 'Hedwig', 'Hedwig was a gift from Hagrid.'),
('pop-culture', 'Star Wars', 'Who is Luke Skywalker''s father?', 'text', NULL, 'Darth Vader', 'Vader reveals his identity in Cloud City.'),
('geography', 'Continents', 'Which is the largest continent?', 'multiple_choice', '["Africa", "North America", "Asia", "Antarctica"]', 'Asia', 'Asia covers 30% of Earth''s land area.'),
('geography', 'Oceans', 'What is the deepest point in the ocean?', 'text', NULL, 'Mariana Trench', 'Located in the western Pacific Ocean.'),
('geography', 'Countries', 'China is the most populous country.', 'boolean', NULL, 'False', 'India surpassed China in 2023.'),
('geography', 'Rivers', 'What is the longest river in the world?', 'multiple_choice', '["Amazon", "Nile", "Yangtze", "Mississippi"]', 'Nile', 'The Nile is traditionally considered the longest.'),
('geography', 'Capitals', 'What is the capital of Australia?', 'multiple_choice', '["Sydney", "Melbourne", "Canberra", "Perth"]', 'Canberra', 'Canberra was a compromise capital.'),
('geography', 'Mountains', 'Mount Everest is the tallest mountain.', 'boolean', NULL, 'True', 'Its peak is 8,848 meters above sea level.'),
('geography', 'Deserts', 'Which is the largest hot desert?', 'text', NULL, 'Sahara', 'It covers much of North Africa.'),
('geography', 'Islands', 'Japan is known as the Land of the Rising Sun.', 'boolean', NULL, 'True', 'The name "Nippon" means sun origin.'),
('geography', 'Lakes', 'Which is the largest freshwater lake by area?', 'multiple_choice', '["Victoria", "Superior", "Caspian", "Baikal"]', 'Superior', 'Lake Superior is the largest of the Great Lakes.'),
('geography', 'USA', 'How many states are in the USA?', 'text', NULL, '50', 'Hawaii was the last to join in 1959.'),
('sports', 'Olympics', 'How often are Summer Olympics held?', 'multiple_choice', '["Every 2 years", "Every 4 years", "Every 5 years", "Every year"]', 'Every 4 years', 'The games occur in a four-year cycle.'),
('sports', 'Soccer', 'Brazil has won the most World Cups.', 'boolean', NULL, 'True', 'Brazil has five titles.'),
('sports', 'Basketball', 'How many players per team are on court?', 'text', NULL, '5', 'Standard games feature 5v5 play.'),
('sports', 'Tennis', 'Which tournament is on grass?', 'multiple_choice', '["French Open", "US Open", "Wimbledon", "Australian Open"]', 'Wimbledon', 'Wimbledon is the oldest grass tournament.'),
('sports', 'Golf', 'What is one under par called?', 'text', NULL, 'Birdie', 'A birdie is one stroke less than par.'),
('sports', 'Baseball', 'A standard game has 9 innings.', 'boolean', NULL, 'True', 'Unless tied or shortened by weather.'),
('sports', 'Boxing', 'Who is known as "The Greatest"?', 'text', NULL, 'Muhammad Ali', 'Ali is a global sports icon.'),
('sports', 'Formula 1', 'Who has 7 F1 titles (tied)?', 'multiple_choice', '["Schumacher", "Hamilton", "Senna", "Vettel"]', 'Hamilton', 'Hamilton and Schumacher share the record.'),
('sports', 'Hockey', 'The object hit in hockey is a puck.', 'boolean', NULL, 'True', 'It is made of vulcanized rubber.'),
('sports', 'American Football', 'How many points is a touchdown?', 'text', NULL, '6', 'Plus an extra point or conversion attempt.'),
('history', 'American Revolution', 'Which city served as the first capital of the United States?', 'multiple_choice', '["New York City", "Philadelphia", "Washington D.C.", "Boston"]', 'New York City', 'New York City was the capital from 1785 to 1790.'),
('history', 'Black Death', 'The Black Death was caused by which type of organism?', 'multiple_choice', '["Virus", "Bacteria", "Fungus", "Parasite"]', 'Bacteria', 'Yersinia pestis is the bacterium responsible.'),
('history', 'Ancient Greece', 'Athens is considered the birthplace of democracy.', 'boolean', NULL, 'True', 'Cleisthenes introduced democratic reforms in 508 BC.'),
('history', 'World War I', 'Which event triggered the start of World War I?', 'text', NULL, 'Assassination of Archduke Franz Ferdinand', 'The assassination occurred in Sarajevo in 1914.'),
('history', 'Civil Rights', 'Who refused to give up her bus seat in Montgomery?', 'text', NULL, 'Rosa Parks', 'Her action sparked the Montgomery Bus Boycott.'),
('history', 'Cold War', 'The Space Race was a competition between the US and USSR.', 'boolean', NULL, 'True', 'It focused on achievements in space exploration.'),
('history', 'Renaissance', 'Who painted the Mona Lisa?', 'multiple_choice', '["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"]', 'Leonardo da Vinci', 'Painted in the early 16th century.'),
('history', 'Russian Revolution', 'In what year did the Russian Revolution take place?', 'text', NULL, '1917', 'It led to the rise of the Soviet Union.'),
('history', 'Mayan Civilization', 'The Maya were known for their advanced calendar system.', 'boolean', NULL, 'True', 'Their calendar was highly accurate and complex.'),
('history', 'Mongol Empire', 'Who founded the Mongol Empire?', 'text', NULL, 'Genghis Khan', 'He unified the Mongol tribes in 1206.'),
('science', 'Physics', 'Who is known for the theory of general relativity?', 'multiple_choice', '["Newton", "Einstein", "Hawking", "Galileo"]', 'Einstein', 'Einstein published the theory in 1915.'),
('science', 'Chemistry', 'The atomic number of Oxygen is 8.', 'boolean', NULL, 'True', 'Oxygen has 8 protons in its nucleus.'),
('science', 'Biology', 'What is the largest bone in the human body?', 'text', NULL, 'Femur', 'The femur is the thigh bone.'),
('science', 'Astronomy', 'Which is the closest star to Earth?', 'multiple_choice', '["Proxima Centauri", "Alpha Centauri", "Sirius", "The Sun"]', 'The Sun', 'The Sun is about 93 million miles away.'),
('science', 'Geology', 'Diamonds are made of which element?', 'text', NULL, 'Carbon', 'Diamonds are a solid form of pure carbon.'),
('science', 'Space', 'The Moon has its own light source.', 'boolean', NULL, 'False', 'The Moon reflects light from the Sun.'),
('science', 'Botany', 'What is the name of the green pigment in plants?', 'multiple_choice', '["Carotene", "Anthocyanin", "Chlorophyll", "Xanthophyll"]', 'Chlorophyll', 'It is essential for photosynthesis.'),
('science', 'Zoology', 'What is the only mammal capable of true flight?', 'text', NULL, 'Bat', 'Bats have modified forelimbs that act as wings.'),
('science', 'Physics', 'Sound travels faster than light.', 'boolean', NULL, 'False', 'Light is much faster than sound.'),
('science', 'Chemistry', 'What is the pH level of a neutral substance?', 'text', NULL, '7', 'Pure water has a pH of 7.'),
('pop-culture', 'Movies', 'Who played the Joker in "The Dark Knight"?', 'multiple_choice', '["Jack Nicholson", "Heath Ledger", "Joaquin Phoenix", "Jared Leto"]', 'Heath Ledger', 'Ledger won a posthumous Oscar for the role.'),
('pop-culture', 'Music', 'The "King of Rock and Roll" is Elvis Presley.', 'boolean', NULL, 'True', 'Presley is a cultural icon of the 20th century.'),
('pop-culture', 'TV Shows', 'What is the name of the fictional town in "Stranger Things"?', 'text', NULL, 'Hawkins', 'The show is set in Hawkins, Indiana.'),
('pop-culture', 'Internet', 'Who co-founded Microsoft with Bill Gates?', 'multiple_choice', '["Steve Jobs", "Paul Allen", "Jeff Bezos", "Larry Page"]', 'Paul Allen', 'They founded the company in 1975.'),
('pop-culture', 'Gaming', 'What is the name of the main character in "Halo"?', 'text', NULL, 'Master Chief', 'Also known as John-117.'),
('pop-culture', 'Books', '"The Great Gatsby" was written by F. Scott Fitzgerald.', 'boolean', NULL, 'True', 'Published in 1925.'),
('pop-culture', 'Animation', 'Which studio created "Toy Story"?', 'multiple_choice', '["Disney", "DreamWorks", "Pixar", "Blue Sky"]', 'Pixar', 'It was the first fully computer-animated feature.'),
('pop-culture', 'Comics', 'Spider-Man''s secret identity is Peter Parker.', 'text', NULL, 'Peter Parker', 'Created by Stan Lee and Steve Ditko.'),
('pop-culture', 'Streaming', 'Netflix started as a DVD-by-mail service.', 'boolean', NULL, 'True', 'It launched in 1997.'),
('pop-culture', 'Movies', 'Which movie features the line "I''ll be back"?', 'text', NULL, 'The Terminator', 'Spoken by Arnold Schwarzenegger.'),
('geography', 'Landmarks', 'Where is the Great Pyramid of Giza located?', 'multiple_choice', '["Mexico", "Egypt", "Peru", "China"]', 'Egypt', 'It is the oldest of the Seven Wonders.'),
('geography', 'Continents', 'Europe is the smallest continent.', 'boolean', NULL, 'False', 'Australia is the smallest continent.'),
('geography', 'Cities', 'What is the capital of France?', 'text', NULL, 'Paris', 'Paris is known as the City of Light.'),
('geography', 'Oceans', 'Which ocean is the largest?', 'multiple_choice', '["Atlantic", "Indian", "Arctic", "Pacific"]', 'Pacific', 'It covers 1/3 of the Earth''s surface.'),
('geography', 'Mountains', 'What is the longest mountain range?', 'text', NULL, 'Andes', 'Located in South America.'),
('geography', 'Rivers', 'The Mississippi River is the longest in the world.', 'boolean', NULL, 'False', 'The Nile is longer.'),
('geography', 'Countries', 'Which country has the most time zones?', 'multiple_choice', '["Russia", "USA", "France", "China"]', 'France', 'Including its overseas territories.'),
('geography', 'Islands', 'What is the largest island in the world?', 'text', NULL, 'Greenland', 'Australia is considered a continent, not an island.'),
('geography', 'Lakes', 'Lake Baikal is the deepest lake in the world.', 'boolean', NULL, 'True', 'Located in southern Siberia, Russia.'),
('geography', 'Deserts', 'Which country is the Gobi Desert primarily in?', 'text', NULL, 'Mongolia', 'Also covers parts of northern China.'),
('sports', 'Soccer', 'Which country won the 2022 FIFA World Cup?', 'multiple_choice', '["France", "Brazil", "Argentina", "Germany"]', 'Argentina', 'Led by Lionel Messi to their third title.'),
('sports', 'Basketball', 'LeBron James has won 4 NBA titles.', 'boolean', NULL, 'True', 'Titles with Miami, Cleveland, and LA.'),
('sports', 'Tennis', 'How many Grand Slam tournaments are there per year?', 'text', NULL, '4', 'Australian Open, French Open, Wimbledon, US Open.'),
('sports', 'Golf', 'What is the name of the most famous golf tournament in Georgia, USA?', 'multiple_choice', '["The Open", "US Open", "The Masters", "PGA Championship"]', 'The Masters', 'Held annually at Augusta National.'),
('sports', 'Baseball', 'Who holds the record for most career home runs in MLB?', 'text', NULL, 'Barry Bonds', 'Bonds hit 762 home runs.'),
('sports', 'Boxing', 'Mike Tyson was the youngest heavyweight champion.', 'boolean', NULL, 'True', 'He won the title at age 20.'),
('sports', 'Olympics', 'Which city hosted the first modern Olympics in 1896?', 'multiple_choice', '["Paris", "London", "Athens", "Rome"]', 'Athens', 'Returning to the birthplace of the games.'),
('sports', 'Cycling', 'What color jersey does the leader of the Tour de France wear?', 'text', NULL, 'Yellow', 'The "maillot jaune".'),
('sports', 'Hockey', 'Wayne Gretzky is known as "The Great One".', 'boolean', NULL, 'True', 'He holds almost every major NHL record.'),
('sports', 'Cricket', 'Which country won the first ever Cricket World Cup?', 'text', NULL, 'West Indies', 'They won the inaugural 1975 tournament.'),
('history', 'Space Race', 'Who was the first human to travel into space?', 'multiple_choice', '["Neil Armstrong", "Yuri Gagarin", "John Glenn", "Buzz Aldrin"]', 'Yuri Gagarin', 'Gagarin orbited the Earth in 1961.'),
('history', 'Titanic', 'In what year did the Titanic sink?', 'text', NULL, '1912', 'The ship hit an iceberg on its maiden voyage.'),
('history', 'Ancient Rome', 'The city of Pompeii was destroyed by which volcano?', 'text', NULL, 'Mount Vesuvius', 'The eruption occurred in 79 AD.'),
('history', 'World War II', 'Which country was the first to be invaded by Germany in WWII?', 'text', NULL, 'Poland', 'The invasion began on September 1, 1939.'),
('history', 'Vietnam War', 'The Fall of Saigon marked the end of the Vietnam War.', 'boolean', NULL, 'True', 'Saigon fell to North Vietnamese forces in 1975.'),
('history', 'French Revolution', 'Who was the Queen of France during the revolution?', 'text', NULL, 'Marie Antoinette', 'She was executed by guillotine in 1793.'),
('history', 'Cold War', 'The "Iron Curtain" was a term coined by Winston Churchill.', 'boolean', NULL, 'True', 'He used the term in a 1946 speech.'),
('history', 'Industrial Revolution', 'Which country did the Industrial Revolution begin in?', 'multiple_choice', '["USA", "France", "Germany", "Great Britain"]', 'Great Britain', 'It began in the late 18th century.'),
('history', 'Magna Carta', 'The Magna Carta limited the power of the King.', 'boolean', NULL, 'True', 'It established that the King was not above the law.'),
('history', 'Great Wall', 'Who was the first Emperor of China who began the Great Wall?', 'text', NULL, 'Qin Shi Huang', 'He unified China in 221 BC.'),
('science', 'Space', 'What is the hottest planet in our solar system?', 'multiple_choice', '["Mercury", "Venus", "Mars", "Jupiter"]', 'Venus', 'Venus has a thick atmosphere that traps heat.'),
('science', 'Physics', 'Isaac Newton discovered the laws of motion.', 'boolean', NULL, 'True', 'His "Principia" was published in 1687.'),
('science', 'Chemistry', 'What is the most abundant element in the universe?', 'multiple_choice', '["Oxygen", "Carbon", "Helium", "Hydrogen"]', 'Hydrogen', 'Hydrogen makes up about 75% of elemental mass.'),
('science', 'Biology', 'What part of the brain controls balance?', 'text', NULL, 'Cerebellum', 'Located at the back of the skull.'),
('science', 'Geology', 'What is the scale used to measure earthquake magnitude?', 'text', NULL, 'Richter Scale', 'Also the Moment Magnitude Scale is used.'),
('science', 'Astronomy', 'A light-year is a unit of time.', 'boolean', NULL, 'False', 'It is a unit of distance.'),
('science', 'Botany', 'Which part of the plant conducts photosynthesis?', 'multiple_choice', '["Root", "Stem", "Leaf", "Flower"]', 'Leaf', 'Leaves contain the most chlorophyll.'),
('science', 'Zoology', 'What is the largest land animal?', 'text', NULL, 'African Elephant', 'The African Bush Elephant is the largest.'),
('science', 'Physics', 'Energy cannot be created or destroyed.', 'boolean', NULL, 'True', 'This is the Law of Conservation of Energy.'),
('science', 'Chemistry', 'What is the common name for Sodium Chloride?', 'text', NULL, 'Salt', 'Used as a seasoning and preservative.'),
('pop-culture', 'Movies', 'What was the first movie in the MCU?', 'multiple_choice', '["Thor", "Captain America", "Iron Man", "The Avengers"]', 'Iron Man', 'Released in 2008 starring Robert Downey Jr.'),
('pop-culture', 'Music', 'The "Fab Four" refers to The Beatles.', 'boolean', NULL, 'True', 'John, Paul, George, and Ringo.'),
('pop-culture', 'TV Shows', 'Who is the protagonist of "Breaking Bad"?', 'text', NULL, 'Walter White', 'A chemistry teacher turned drug lord.'),
('pop-culture', 'Internet', 'What is the most visited website in the world?', 'multiple_choice', '["Facebook", "YouTube", "Google", "Amazon"]', 'Google', 'It is the primary search engine for most people.'),
('pop-culture', 'Gaming', 'What is the name of the princess in "Super Mario"?', 'text', NULL, 'Peach', 'Also known as Princess Toadstool.'),
('pop-culture', 'Books', 'Who wrote the "Harry Potter" series?', 'text', NULL, 'J.K. Rowling', 'The series consists of seven books.'),
('pop-culture', 'Animation', '"The Simpsons" is the longest-running scripted US TV show.', 'boolean', NULL, 'True', 'It has been on air since 1989.'),
('pop-culture', 'Comics', 'What is the home city of Batman?', 'multiple_choice', '["Metropolis", "Central City", "Gotham City", "Star City"]', 'Gotham City', 'A fictional city inspired by NYC and Chicago.'),
('pop-culture', 'Streaming', 'Which platform produces "The Mandalorian"?', 'text', NULL, 'Disney+', 'A live-action Star Wars series.'),
('pop-culture', 'Movies', 'Who directed "Inception"?', 'multiple_choice', '["Spielberg", "Nolan", "Tarantino", "Scorsese"]', 'Christopher Nolan', 'Released in 2010.'),
('geography', 'Landmarks', 'Where is the Statue of Liberty located?', 'multiple_choice', '["Washington", "Boston", "New York", "Philadelphia"]', 'New York', 'A gift from France to the US.'),
('geography', 'Continents', 'Asia is the most populous continent.', 'boolean', NULL, 'True', 'It holds over 60% of the world population.'),
('geography', 'Cities', 'What is the capital of Japan?', 'text', NULL, 'Tokyo', 'The most populous metropolitan area.'),
('geography', 'Oceans', 'Which ocean is between Africa and Australia?', 'multiple_choice', '["Atlantic", "Pacific", "Indian", "Arctic"]', 'Indian', 'The third-largest ocean.'),
('geography', 'Mountains', 'The Himalayas are in Asia.', 'boolean', NULL, 'True', 'They contain the world''s highest peaks.'),
('geography', 'Rivers', 'Which river flows through Egypt?', 'text', NULL, 'Nile', 'The lifeline of Ancient Egypt.'),
('geography', 'Countries', 'Which country is also a continent?', 'text', NULL, 'Australia', 'The "Land Down Under".'),
('geography', 'Islands', 'Which island is part of the US state of Hawaii?', 'multiple_choice', '["Bali", "Fiji", "Maui", "Tahiti"]', 'Maui', 'Known for its stunning beaches and volcanoes.'),
('geography', 'Lakes', 'Lake Victoria is the largest lake in Africa.', 'boolean', NULL, 'True', 'It is the world''s largest tropical lake.'),
('geography', 'Deserts', 'Which is the largest cold desert in the world?', 'text', NULL, 'Antarctica', 'Covers the entire continent.'),
('sports', 'Soccer', 'Who has the most Ballon d''Or awards?', 'multiple_choice', '["Messi", "Ronaldo", "Cruyff", "Platini"]', 'Messi', 'Lionel Messi holds the record.'),
('sports', 'Basketball', 'The "Dream Team" played in the 1992 Olympics.', 'boolean', NULL, 'True', 'The first US Olympic team with active NBA players.'),
('sports', 'Tennis', 'What is the nickname for the French Open?', 'text', NULL, 'Roland Garros', 'Named after a French aviator.'),
('sports', 'Golf', 'Tiger Woods has won 15 major championships.', 'boolean', NULL, 'True', 'Second all-time behind Jack Nicklaus.'),
('sports', 'Baseball', 'What is the name of the New York MLB team?', 'multiple_choice', '["Red Sox", "Cubs", "Yankees", "Dodgers"]', 'Yankees', 'One of the two MLB teams in NYC.'),
('sports', 'Boxing', 'Who was the first boxer to win the world heavyweight title three times?', 'text', NULL, 'Muhammad Ali', 'He won in 1964, 1974, and 1978.'),
('sports', 'Olympics', 'The Olympic rings represent the five continents.', 'boolean', NULL, 'True', 'Africa, Americas, Asia, Europe, Oceania.'),
('sports', 'Cycling', 'What is the most famous cycling race in the world?', 'text', NULL, 'Tour de France', 'A multi-stage race held annually in France.'),
('sports', 'Hockey', 'How many players are on the ice per team in the NHL?', 'text', NULL, '6', 'Including the goaltender.'),
('sports', 'American Football', 'Who has the most Super Bowl rings as a player?', 'text', NULL, 'Tom Brady', 'He has won 7 Super Bowls.'),
('history', 'Ancient Egypt', 'What was the process of preserving a body called?', 'text', NULL, 'Mummification', 'It involved removing organs and wrapping the body in linen.'),
('history', 'Civil War', 'The Battle of Gettysburg was a major turning point.', 'boolean', NULL, 'True', 'It occurred in July 1863 in Pennsylvania.'),
('history', 'Renaissance', 'Who was the famous sculptor of the "David" statue?', 'multiple_choice', '["Donatello", "Bernini", "Michelangelo", "Canova"]', 'Michelangelo', 'Completed between 1501 and 1504.'),
('history', 'Space Race', 'What was the name of the first satellite launched into orbit?', 'text', NULL, 'Sputnik 1', 'Launched by the Soviet Union in 1957.'),
('history', 'French Revolution', 'The guillotine was the primary method of execution.', 'boolean', NULL, 'True', 'It was considered a more "humane" method at the time.'),
('history', 'World War I', 'What was the nickname for German submarines?', 'text', NULL, 'U-boats', 'Short for "Unterseeboot".'),
('history', 'Ancient Greece', 'Who was the Greek god of the sea?', 'multiple_choice', '["Zeus", "Hades", "Poseidon", "Apollo"]', 'Poseidon', 'Brother of Zeus and Hades.'),
('history', 'Mayan Civilization', 'The Maya were located in Central America.', 'boolean', NULL, 'True', 'Primarily in modern-day Mexico, Guatemala, and Belize.'),
('history', 'Industrial Revolution', 'Who patented the first telephone?', 'text', NULL, 'Alexander Graham Bell', 'He received the patent in 1876.'),
('history', 'Rome', 'Romulus and Remus were the legendary founders of Rome.', 'boolean', NULL, 'True', 'According to myth, they were raised by a she-wolf.'),
('science', 'Physics', 'Who discovered gravity after watching an apple fall?', 'multiple_choice', '["Einstein", "Galileo", "Newton", "Tesla"]', 'Newton', 'Sir Isaac Newton formulated the law of universal gravitation.'),
('science', 'Biology', 'What is the largest organ of the human body?', 'text', NULL, 'Skin', 'It protects the body and regulates temperature.'),
('science', 'Chemistry', 'Helium is the lightest element.', 'boolean', NULL, 'False', 'Hydrogen is the lightest element.'),
('science', 'Astronomy', 'Which planet is famous for its prominent rings?', 'multiple_choice', '["Jupiter", "Saturn", "Uranus", "Neptune"]', 'Saturn', 'The rings are mostly made of ice and dust.'),
('science', 'Geology', 'What is the name for molten rock underground?', 'text', NULL, 'Magma', 'Once it reaches the surface, it is called lava.'),
('science', 'Mathematics', 'A triangle with three equal sides is called equilateral.', 'boolean', NULL, 'True', 'All internal angles are 60 degrees.'),
('science', 'Zoology', 'Which animal is known as the "King of the Jungle"?', 'text', NULL, 'Lion', 'Though they primarily live in savannas.'),
('science', 'Space', 'The Milky Way is a spiral galaxy.', 'boolean', NULL, 'True', 'It contains 100-400 billion stars.'),
('science', 'Botany', 'What do bees collect from flowers to make honey?', 'multiple_choice', '["Pollen", "Sap", "Nectar", "Seed"]', 'Nectar', 'Nectar is a sugar-rich liquid.'),
('science', 'Chemistry', 'What is the chemical symbol for Silver?', 'text', NULL, 'Ag', 'From the Latin "argentum".'),
('pop-culture', 'Movies', 'Who directed "Jurassic Park"?', 'multiple_choice', '["Spielberg", "Lucas", "Cameron", "Jackson"]', 'Spielberg', 'Released in 1993, it was a landmark for CGI.'),
('pop-culture', 'Music', 'Katy Perry sang "Firework".', 'boolean', NULL, 'True', 'A hit single from her album "Teenage Dream".'),
('pop-culture', 'TV Shows', 'What is the name of the main dragon in "Game of Thrones"?', 'text', NULL, 'Drogon', 'The largest of Daenerys'' three dragons.'),
('pop-culture', 'Gaming', 'What is the best-selling handheld console?', 'multiple_choice', '["Game Boy", "PSP", "Nintendo DS", "Switch"]', 'Nintendo DS', 'It sold over 154 million units.'),
('pop-culture', 'Comics', 'Wolverine is a member of the X-Men.', 'boolean', NULL, 'True', 'He first appeared in Incredible Hulk #180.'),
('pop-culture', 'Internet', 'Who founded Facebook?', 'text', NULL, 'Mark Zuckerberg', 'Originally launched as "TheFacebook".'),
('pop-culture', 'Movies', 'What is the name of the kingdom in "Frozen"?', 'multiple_choice', '["Arendelle", "Corona", "Atlantica", "DunBroch"]', 'Arendelle', 'Inspired by Norwegian landscapes.'),
('pop-culture', 'Books', 'Sherlock Holmes lived at 221B Baker Street.', 'boolean', NULL, 'True', 'A fictional address created by Arthur Conan Doyle.'),
('pop-culture', 'Music', 'Which band released "Bohemian Rhapsody"?', 'text', NULL, 'Queen', 'Written by Freddie Mercury.'),
('pop-culture', 'Gaming', 'Master Chief is the hero of "Halo".', 'boolean', NULL, 'True', 'He is a Spartan super-soldier.'),
('geography', 'Countries', 'Which country has the largest area?', 'multiple_choice', '["USA", "China", "Canada", "Russia"]', 'Russia', 'It covers over 17 million square km.'),
('geography', 'Oceans', 'The Atlantic Ocean is deeper than the Pacific.', 'boolean', NULL, 'False', 'The Pacific is deeper on average.'),
('geography', 'Cities', 'What is the capital of Italy?', 'text', NULL, 'Rome', 'Known as the "Eternal City".'),
('geography', 'Continents', 'Which continent is entirely in the Southern Hemisphere?', 'multiple_choice', '["Africa", "South America", "Australia", "Europe"]', 'Australia', 'Also known as the "Island Continent".'),
('geography', 'Landmarks', 'Where is the Taj Mahal located?', 'text', NULL, 'India', 'Built by Emperor Shah Jahan.'),
('geography', 'Rivers', 'The Amazon River is in South America.', 'boolean', NULL, 'True', 'It is the largest river by discharge volume.'),
('geography', 'Mountains', 'What is the name of the mountain range in the western US?', 'multiple_choice', '["Appalachians", "Alps", "Rockies", "Andes"]', 'Rockies', 'Extending from Canada to New Mexico.'),
('geography', 'Islands', 'Madagascar is off the coast of Africa.', 'boolean', NULL, 'True', 'The fourth-largest island in the world.'),
('geography', 'Capitals', 'What is the capital of Canada?', 'text', NULL, 'Ottawa', 'Located in Ontario.'),
('geography', 'Deserts', 'The Sahara is the largest hot desert.', 'boolean', NULL, 'True', 'It covers about 31% of Africa.'),
('sports', 'Basketball', 'Who is known as "His Airness"?', 'multiple_choice', '["Kobe", "LeBron", "Jordan", "Curry"]', 'Jordan', 'Michael Jordan won 6 NBA titles.'),
('sports', 'Soccer', 'A penalty kick is taken from 12 yards out.', 'boolean', NULL, 'True', 'Standard distance in professional soccer.'),
('sports', 'Tennis', 'What is the surface at the US Open?', 'text', NULL, 'Hard court', 'A fast surface made of acrylic.'),
('sports', 'Golf', 'What is the term for three strokes under par?', 'multiple_choice', '["Eagle", "Birdie", "Albatross", "Bogey"]', 'Albatross', 'Extremely rare in professional play.'),
('sports', 'Olympics', 'Michael Phelps has won the most gold medals.', 'boolean', NULL, 'True', 'He has 23 Olympic gold medals.'),
('sports', 'Baseball', 'How many bases are on a baseball field?', 'text', NULL, '4', 'First, second, third, and home plate.'),
('sports', 'Boxing', 'Who was known as the "Brown Bomber"?', 'text', NULL, 'Joe Louis', 'One of the greatest heavyweights.'),
('sports', 'Formula 1', 'Where is the famous street circuit Grand Prix held?', 'multiple_choice', '["Silverstone", "Monza", "Monaco", "Suzuka"]', 'Monaco', 'Known for its tight turns and prestige.'),
('sports', 'Hockey', 'Ice hockey originated in Canada.', 'boolean', NULL, 'True', 'Developed in the mid-19th century.'),
('sports', 'Cricket', 'How many players are in a cricket team?', 'text', NULL, '11', 'Same as a standard soccer team.'),
('history', 'American Revolution', 'Who was the primary author of the Declaration of Independence?', 'text', NULL, 'Thomas Jefferson', 'He drafted the document in June 1776.'),
('history', 'Ancient Egypt', 'The Sphinx has the body of a lion and the head of a human.', 'boolean', NULL, 'True', 'It is one of the most famous statues in the world.'),
('history', 'Renaissance', 'Which city is considered the cradle of the Renaissance?', 'multiple_choice', '["Rome", "Venice", "Florence", "Milan"]', 'Florence', 'The Medici family were major patrons of the arts there.'),
('history', 'Vietnam War', 'What was the name of the North Vietnamese leader?', 'text', NULL, 'Ho Chi Minh', 'Saigon was renamed in his honor in 1976.'),
('history', 'Black Death', 'The plague originated in Asia.', 'boolean', NULL, 'True', 'It spread along trade routes like the Silk Road.'),
('history', 'Ancient Rome', 'Who was the general who crossed the Alps with elephants?', 'text', NULL, 'Hannibal', 'A Carthaginian leader during the Second Punic War.'),
('history', 'Civil Rights', 'Martin Luther King Jr. delivered his "I Have a Dream" speech in which city?', 'multiple_choice', '["Atlanta", "Memphis", "Birmingham", "Washington D.C."]', 'Washington D.C.', 'Delivered at the Lincoln Memorial in 1963.'),
('history', 'Industrial Revolution', 'Which invention allowed for rapid communication across distances?', 'text', NULL, 'Telegraph', 'Developed by Samuel Morse and others.'),
('history', 'World War II', 'Hiroshima and Nagasaki were the two cities hit by atomic bombs.', 'boolean', NULL, 'True', 'Dropped by the US in August 1945.'),
('history', 'Ancient Greece', 'What was the name of the temple dedicated to Athena in Athens?', 'text', NULL, 'Parthenon', 'Located on the Acropolis.'),
('science', 'Physics', 'What is the unit of force?', 'multiple_choice', '["Joule", "Watt", "Newton", "Pascal"]', 'Newton', 'Named after Sir Isaac Newton.'),
('science', 'Biology', 'Humans have 46 chromosomes.', 'boolean', NULL, 'True', 'Arranged in 23 pairs.'),
('science', 'Chemistry', 'What is the most common element in the Earth''s crust?', 'multiple_choice', '["Iron", "Silicon", "Oxygen", "Aluminum"]', 'Oxygen', 'Oxygen makes up nearly 47% of the crust by mass.'),
('science', 'Astronomy', 'What is the name of the closest galaxy to the Milky Way?', 'text', NULL, 'Andromeda', 'Expected to collide with our galaxy in 4 billion years.'),
('science', 'Geology', 'The Earth''s core is mostly made of iron and nickel.', 'boolean', NULL, 'True', 'It is divided into inner and outer cores.'),
('science', 'Mathematics', 'What is the value of Pi (to two decimal places)?', 'text', NULL, '3.14', 'The ratio of a circle''s circumference to its diameter.'),
('science', 'Zoology', 'What is the fastest land animal?', 'text', NULL, 'Cheetah', 'Can reach speeds of up to 70 mph.'),
('science', 'Space', 'Which mission landed the first humans on the Moon?', 'multiple_choice', '["Apollo 7", "Apollo 11", "Apollo 13", "Gemini 4"]', 'Apollo 11', 'Landed in the Sea of Tranquility in 1969.'),
('science', 'Botany', 'Fungi are a type of plant.', 'boolean', NULL, 'False', 'Fungi have their own biological kingdom.'),
('science', 'Chemistry', 'What is the chemical symbol for Lead?', 'text', NULL, 'Pb', 'From the Latin "plumbum".'),
('pop-culture', 'Movies', 'Which movie features the character Darth Vader?', 'multiple_choice', '["Star Trek", "Star Wars", "Guardians of the Galaxy", "Dune"]', 'Star Wars', 'An iconic villain created by George Lucas.'),
('pop-culture', 'Music', 'Madonna is known as the "Queen of Pop".', 'boolean', NULL, 'True', 'One of the most influential female artists.'),
('pop-culture', 'TV Shows', 'Which show features a group of survivors in a zombie apocalypse?', 'text', NULL, 'The Walking Dead', 'Based on the comic book series.'),
('pop-culture', 'Internet', 'Which social media platform uses a bird as its logo?', 'text', NULL, 'Twitter', 'Now rebranded to X.'),
('pop-culture', 'Gaming', 'What is the name of the main character in "Tomb Raider"?', 'multiple_choice', '["Lara Croft", "Jill Valentine", "Samus Aran", "Bayonetta"]', 'Lara Croft', 'A famous British archaeologist.'),
('pop-culture', 'Books', 'Who wrote "1984"?', 'text', NULL, 'George Orwell', 'A dystopian novel published in 1949.'),
('pop-culture', 'Animation', 'SpongeBob SquarePants lives in a pineapple under the sea.', 'boolean', NULL, 'True', 'The show debuted on Nickelodeon in 1999.'),
('pop-culture', 'Comics', 'What is the real name of Iron Man?', 'text', NULL, 'Tony Stark', 'A billionaire industrialist and genius inventor.'),
('pop-culture', 'Streaming', 'Which service is known for "Stranger Things" and "The Crown"?', 'multiple_choice', '["Hulu", "HBO Max", "Netflix", "Prime Video"]', 'Netflix', 'A pioneer in streaming content.'),
('pop-culture', 'Movies', 'Who played Jack in "Titanic"?', 'text', NULL, 'Leonardo DiCaprio', 'Co-starred with Kate Winslet.'),
('geography', 'Landmarks', 'Where is Machu Picchu located?', 'multiple_choice', '["Chile", "Peru", "Bolivia", "Ecuador"]', 'Peru', 'An Incan citadel in the Andes Mountains.'),
('geography', 'Continents', 'Africa is the second largest continent.', 'boolean', NULL, 'True', 'After Asia.'),
('geography', 'Cities', 'What is the capital of Japan?', 'text', NULL, 'Tokyo', 'Known for its high-tech culture.'),
('geography', 'Oceans', 'The Indian Ocean is the smallest major ocean.', 'boolean', NULL, 'False', 'The Arctic Ocean is the smallest.'),
('geography', 'Mountains', 'What is the tallest mountain in North America?', 'multiple_choice', '["Mount Rainier", "Mount Whitney", "Denali", "Mount Logan"]', 'Denali', 'Formerly known as Mount McKinley.'),
('geography', 'Rivers', 'The Ganges River is sacred in which religion?', 'text', NULL, 'Hinduism', 'Flows through India and Bangladesh.'),
('geography', 'Countries', 'Brazil is the largest country in South America.', 'boolean', NULL, 'True', 'Covers nearly half of the continent.'),
('geography', 'Islands', 'What is the largest country in the world by island count?', 'text', NULL, 'Sweden', 'Has over 260,000 islands.'),
('geography', 'Capitals', 'What is the capital of Spain?', 'multiple_choice', '["Barcelona", "Seville", "Valencia", "Madrid"]', 'Madrid', 'Located in the center of the country.'),
('geography', 'Deserts', 'The Atacama Desert is the driest non-polar place on Earth.', 'boolean', NULL, 'True', 'Located in Chile.'),
('sports', 'Soccer', 'Which team has won the most UEFA Champions League titles?', 'text', NULL, 'Real Madrid', 'They have over 14 titles.'),
('sports', 'Basketball', 'Steph Curry is known for his three-point shooting.', 'boolean', NULL, 'True', 'Considered the greatest shooter in NBA history.'),
('sports', 'Tennis', 'What is the oldest Grand Slam tournament?', 'multiple_choice', '["US Open", "French Open", "Wimbledon", "Australian Open"]', 'Wimbledon', 'First held in 1877.'),
('sports', 'Golf', 'What color jacket is awarded to the winner of The Masters?', 'text', NULL, 'Green', 'The famous Green Jacket.'),
('sports', 'Baseball', 'The "World Series" is the championship of MLB.', 'boolean', NULL, 'True', 'First played in 1903.'),
('sports', 'Boxing', 'Who did Muhammad Ali fight in the "Rumble in the Jungle"?', 'text', NULL, 'George Foreman', 'Held in Zaire in 1974.'),
('sports', 'Olympics', 'The 2024 Summer Olympics will be held in which city?', 'multiple_choice', '["Tokyo", "Los Angeles", "Paris", "Brisbane"]', 'Paris', 'The city will host for the third time.'),
('sports', 'Cycling', 'Lance Armstrong won 7 Tour de France titles (later stripped).', 'boolean', NULL, 'True', 'Stripped due to doping violations.'),
('sports', 'Hockey', 'The Stanley Cup is the trophy for which league?', 'text', NULL, 'NHL', 'The oldest professional sports trophy in North America.'),
('sports', 'American Football', 'What is the name of the NFL championship game?', 'text', NULL, 'Super Bowl', 'The most-watched sporting event in the US.'),
('history', 'Ancient Greece', 'Who was the king of the gods in Greek mythology?', 'text', NULL, 'Zeus', 'He ruled from Mount Olympus.'),
('history', 'American Revolution', 'In what year did the American Revolution begin?', 'text', NULL, '1775', 'The war lasted until 1783.'),
('history', 'Ancient Egypt', 'The Great Pyramid is the only one of the Seven Wonders still largely intact.', 'boolean', NULL, 'True', 'Located on the Giza plateau.'),
('history', 'World War I', 'Which country was a member of the Triple Entente?', 'multiple_choice', '["Germany", "Austria-Hungary", "France", "Ottoman Empire"]', 'France', 'Along with Russia and Great Britain.'),
('history', 'Medieval Europe', 'What was the code of conduct for knights called?', 'text', NULL, 'Chivalry', 'It emphasized bravery, honor, and courtesy.'),
('history', 'Civil Rights', 'Who was the first African American Supreme Court Justice?', 'text', NULL, 'Thurgood Marshall', 'Appointed by Lyndon B. Johnson in 1967.'),
('history', 'Viking Age', 'Vikings were known as skilled seafarers and raiders.', 'boolean', NULL, 'True', 'They originated from Scandinavia.'),
('history', 'Cold War', 'What does USSR stand for?', 'text', NULL, 'Union of Soviet Socialist Republics', 'Dissolved in 1991.'),
('history', 'Ancient Rome', 'Who was the Roman god of war?', 'multiple_choice', '["Mars", "Jupiter", "Neptune", "Vulcan"]', 'Mars', 'Equivalent to the Greek god Ares.'),
('history', 'Space Race', 'Who was the first American to orbit the Earth?', 'text', NULL, 'John Glenn', 'He flew the Friendship 7 in 1962.'),
('science', 'Physics', 'What is the speed of sound at sea level (approximate mph)?', 'multiple_choice', '["500", "767", "1000", "1200"]', '767', 'Also known as Mach 1.'),
('science', 'Biology', 'DNA stands for Deoxyribonucleic Acid.', 'boolean', NULL, 'True', 'The hereditary material in humans.'),
('science', 'Chemistry', 'What is the most abundant gas in the atmosphere?', 'text', NULL, 'Nitrogen', 'Makes up about 78% of the air.'),
('science', 'Astronomy', 'Which planet is known as the "Evening Star"?', 'multiple_choice', '["Mars", "Jupiter", "Venus", "Saturn"]', 'Venus', 'It is the brightest object in the sky after the Sun and Moon.'),
('science', 'Geology', 'What is the name for a scientist who studies earthquakes?', 'text', NULL, 'Seismologist', 'They use instruments like seismographs.'),
('science', 'Mathematics', 'A right angle is 90 degrees.', 'boolean', NULL, 'True', 'Formed by two perpendicular lines.'),
('science', 'Zoology', 'What is the only bird that can fly backwards?', 'text', NULL, 'Hummingbird', 'Due to their unique wing structure.'),
('science', 'Space', 'The Sun is at the center of the solar system.', 'boolean', NULL, 'True', 'The heliocentric model proposed by Copernicus.'),
('science', 'Botany', 'What is the study of trees called?', 'multiple_choice', '["Dendrology", "Mycology", "Ornithology", "Entomology"]', 'Dendrology', 'A branch of botany focused on woody plants.'),
('science', 'Chemistry', 'What is the chemical symbol for Iron?', 'text', NULL, 'Fe', 'From the Latin "ferrum".'),
('pop-culture', 'Movies', 'Who played Forrest Gump?', 'multiple_choice', '["Tom Cruise", "Brad Pitt", "Tom Hanks", "Johnny Depp"]', 'Tom Hanks', 'Hanks won an Oscar for the role.'),
('pop-culture', 'Music', 'Beyoncé was a member of Destiny''s Child.', 'boolean', NULL, 'True', 'A successful girl group before her solo career.'),
('pop-culture', 'TV Shows', 'What is the name of the fictional kingdom in "Game of Thrones"?', 'text', NULL, 'Westeros', 'Most of the action takes place on this continent.'),
('pop-culture', 'Internet', 'Who created the World Wide Web?', 'multiple_choice', '["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Mark Zuckerberg"]', 'Tim Berners-Lee', 'He developed it while working at CERN.'),
('pop-culture', 'Gaming', 'What is the name of the plumber in "Super Mario"?', 'text', NULL, 'Mario', 'His brother is Luigi.'),
('pop-culture', 'Books', 'Who wrote "The Lord of the Rings"?', 'text', NULL, 'J.R.R. Tolkien', 'An epic high-fantasy novel.'),
('pop-culture', 'Animation', 'The Grinch stole Christmas.', 'boolean', NULL, 'True', 'Created by Dr. Seuss.'),
('pop-culture', 'Comics', 'Who is the "Man of Steel"?', 'multiple_choice', '["Iron Man", "Batman", "Superman", "Spider-Man"]', 'Superman', 'An iconic DC Comics superhero.'),
('pop-culture', 'Streaming', 'What is the name of the baby Yoda character in "The Mandalorian"?', 'text', NULL, 'Grogu', 'His real name was revealed in Season 2.'),
('pop-culture', 'Movies', 'Which movie features the song "My Heart Will Go On"?', 'text', NULL, 'Titanic', 'Performed by Celine Dion.'),
('geography', 'Landmarks', 'Where is the Colosseum located?', 'multiple_choice', '["Athens", "Paris", "Rome", "Madrid"]', 'Rome', 'The largest ancient amphitheater ever built.'),
('geography', 'Continents', 'Europe and Asia are part of the same landmass.', 'boolean', NULL, 'True', 'Often referred to as Eurasia.'),
('geography', 'Cities', 'What is the capital of Germany?', 'text', NULL, 'Berlin', 'The largest city in Germany.'),
('geography', 'Oceans', 'Which ocean is the second largest?', 'multiple_choice', '["Pacific", "Atlantic", "Indian", "Arctic"]', 'Atlantic', 'Covers about 20% of Earth''s surface.'),
('geography', 'Mountains', 'What is the highest mountain in Africa?', 'text', NULL, 'Mount Kilimanjaro', 'Located in Tanzania.'),
('geography', 'Rivers', 'The Nile flows into the Mediterranean Sea.', 'boolean', NULL, 'True', 'It is one of the world''s longest rivers.'),
('geography', 'Countries', 'Which country has the largest population in Africa?', 'multiple_choice', '["Egypt", "South Africa", "Nigeria", "Ethiopia"]', 'Nigeria', 'With over 200 million people.'),
('geography', 'Islands', 'Which island is famous for its giant stone statues?', 'text', NULL, 'Easter Island', 'The statues are called Moai.'),
('geography', 'Capitals', 'What is the capital of Russia?', 'text', NULL, 'Moscow', 'The political and economic center of Russia.'),
('geography', 'Deserts', 'The Gobi Desert is in South America.', 'boolean', NULL, 'False', 'It is in Asia, covering parts of China and Mongolia.'),
('sports', 'Soccer', 'How many players are on a soccer team (on the pitch)?', 'multiple_choice', '["9", "10", "11", "12"]', '11', 'Including the goalkeeper.'),
('sports', 'Basketball', 'The NBA was founded in 1946.', 'boolean', NULL, 'True', 'Originally as the BAA.'),
('sports', 'Tennis', 'What is a "Grand Slam" in tennis?', 'text', NULL, 'Winning all four major tournaments in a year', 'The four majors are the pinnacle of the sport.'),
('sports', 'Golf', 'What is the maximum number of clubs a golfer can carry?', 'multiple_choice', '["12", "14", "16", "18"]', '14', 'Standard rule in competitive play.'),
('sports', 'Baseball', 'Who is known as the "Bambino"?', 'text', NULL, 'Babe Ruth', 'One of the greatest baseball players.'),
('sports', 'Boxing', 'A boxing match is divided into rounds.', 'boolean', NULL, 'True', 'Usually 3 minutes each.'),
('sports', 'Olympics', 'Which city hosted the 2012 Summer Olympics?', 'multiple_choice', '["Beijing", "Rio", "London", "Tokyo"]', 'London', 'The first city to host the modern games three times.'),
('sports', 'Cycling', 'The Tour de France ends in which city?', 'text', NULL, 'Paris', 'Traditionally on the Champs-Élysées.'),
('sports', 'Hockey', 'What is the name of the NHL team in Toronto?', 'text', NULL, 'Maple Leafs', 'One of the Original Six teams.'),
('sports', 'American Football', 'How many points is a field goal worth?', 'text', NULL, '3', 'Kicked through the uprights.'),
('history', 'American Revolution', 'What was the final major battle of the American Revolution?', 'multiple_choice', '["Saratoga", "Yorktown", "Bunker Hill", "Trenton"]', 'Yorktown', 'General Cornwallis surrendered to George Washington in 1781.'),
('history', 'Ancient Egypt', 'The Rosetta Stone was key to deciphering hieroglyphics.', 'boolean', NULL, 'True', 'It featured the same text in three different scripts.'),
('history', 'French Revolution', 'What was the name of the prison stormed at the start of the revolution?', 'text', NULL, 'Bastille', 'Stormed on July 14, 1789.'),
('history', 'World War II', 'Which country was known as the "Empire of the Sun"?', 'text', NULL, 'Japan', 'A major Axis power in the Pacific theater.'),
('history', 'Cold War', 'The Marshall Plan was designed to rebuild Europe after WWII.', 'boolean', NULL, 'True', 'Initiated by the US in 1948.'),
('history', 'Renaissance', 'Who is known as the "Father of Humanism"?', 'text', NULL, 'Petrarch', 'An Italian scholar and poet.'),
('history', 'Viking Age', 'Which city was a major Viking trading hub in Ireland?', 'multiple_choice', '["Dublin", "Cork", "Limerick", "Galway"]', 'Dublin', 'Founded by Vikings as "Dyflin" in the 9th century.'),
('history', 'Civil Rights', 'Who was the "Mother of the Civil Rights Movement"?', 'text', NULL, 'Rosa Parks', 'Her arrest sparked the 381-day Montgomery Bus Boycott.'),
('history', 'Ancient Greece', 'Alexander the Great was from which kingdom?', 'multiple_choice', '["Athens", "Sparta", "Macedon", "Thebes"]', 'Macedon', 'He created one of the largest empires in history.'),
('history', 'Ancient Rome', 'The Pax Romana was a long period of relative peace and stability.', 'boolean', NULL, 'True', 'Lasted approximately 200 years, beginning with Augustus.'),
('science', 'Physics', 'What is the speed of light (approximate)?', 'text', NULL, '300,000 km/s', 'The exact speed is 299,792,458 meters per second.'),
('science', 'Biology', 'The human heart has 4 chambers.', 'boolean', NULL, 'True', 'Left and right atria, and left and right ventricles.'),
('science', 'Chemistry', 'What is the chemical symbol for Potassium?', 'multiple_choice', '["P", "Po", "K", "Pt"]', 'K', 'From the Neo-Latin "kalium".'),
('science', 'Astronomy', 'Which is the largest moon of Saturn?', 'text', NULL, 'Titan', 'The only moon known to have a dense atmosphere.'),
('science', 'Geology', 'What is the process of breaking down rocks called?', 'text', NULL, 'Weathering', 'Can be physical, chemical, or biological.'),
('science', 'Mathematics', 'Parallel lines never intersect.', 'boolean', NULL, 'True', 'They remain the same distance apart forever.'),
('science', 'Zoology', 'What is the only land animal that cannot jump?', 'text', NULL, 'Elephant', 'Due to their immense weight and leg structure.'),
('science', 'Space', 'What is the name of the first space shuttle launched by NASA?', 'multiple_choice', '["Discovery", "Challenger", "Columbia", "Atlantis"]', 'Columbia', 'Launched on April 12, 1981.'),
('science', 'Botany', 'Bamboo is the fastest-growing plant in the world.', 'boolean', NULL, 'True', 'Some species can grow up to 35 inches in a single day.'),
('science', 'Chemistry', 'What is the most abundant metal in the Earth''s crust?', 'text', NULL, 'Aluminum', 'Makes up about 8% of the crust by weight.'),
('pop-culture', 'Movies', 'Who played the character Harry Potter?', 'multiple_choice', '["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Tom Felton"]', 'Daniel Radcliffe', 'He starred in all eight films in the series.'),
('pop-culture', 'Music', 'The Beatles released the album "Abbey Road".', 'boolean', NULL, 'True', 'Famous for its iconic cover of the band on a zebra crossing.'),
('pop-culture', 'TV Shows', 'What is the name of the fictional town in "Parks and Recreation"?', 'text', NULL, 'Pawnee', 'Pawnee, Indiana.'),
('pop-culture', 'Internet', 'Which company owns YouTube?', 'multiple_choice', '["Microsoft", "Apple", "Google", "Amazon"]', 'Google', 'Acquired YouTube in 2006 for $1.65 billion.'),
('pop-culture', 'Gaming', 'What is the highest-grossing media franchise of all time?', 'text', NULL, 'Pokémon', 'Includes games, cards, anime, and merchandise.'),
('pop-culture', 'Books', '"To Kill a Mockingbird" was written by Harper Lee.', 'boolean', NULL, 'True', 'Published in 1960 and won the Pulitzer Prize.'),
('pop-culture', 'Animation', 'What is the name of the orange fish in "Finding Nemo"?', 'text', NULL, 'Nemo', 'His father is named Marlin.'),
('pop-culture', 'Comics', 'What is the real name of Black Widow?', 'multiple_choice', '["Natasha Romanoff", "Wanda Maximoff", "Carol Danvers", "Hope van Dyne"]', 'Natasha Romanoff', 'A former KGB assassin and member of the Avengers.'),
('pop-culture', 'Streaming', 'Which platform produces "Squid Game"?', 'text', NULL, 'Netflix', 'A South Korean survival drama series.'),
('pop-culture', 'Movies', 'Which movie won the Best Picture Oscar in 2020?', 'multiple_choice', '["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"]', 'Parasite', 'The first non-English language film to win Best Picture.'),
('geography', 'Landmarks', 'Where is the Burj Khalifa located?', 'text', NULL, 'Dubai', 'The tallest building in the world.'),
('geography', 'Continents', 'Europe is the second smallest continent.', 'boolean', NULL, 'True', 'Only Australia is smaller.'),
('geography', 'Cities', 'What is the capital of South Korea?', 'text', NULL, 'Seoul', 'One of the most tech-forward cities in the world.'),
('geography', 'Oceans', 'Which ocean is the saltiest?', 'multiple_choice', '["Pacific", "Atlantic", "Indian", "Arctic"]', 'Atlantic', 'Due to high evaporation rates.'),
('geography', 'Mountains', 'What is the highest mountain in North America?', 'text', NULL, 'Denali', 'Formerly known as Mount McKinley.'),
('geography', 'Rivers', 'The Thames River flows through which city?', 'multiple_choice', '["Paris", "London", "Berlin", "Vienna"]', 'London', 'An iconic river in England.'),
('geography', 'Countries', 'Which country has the most lakes in the world?', 'text', NULL, 'Canada', 'Contains about 60% of the world''s lakes.'),
('geography', 'Islands', 'Which is the largest island in the Caribbean?', 'multiple_choice', '["Jamaica", "Hispaniola", "Cuba", "Puerto Rico"]', 'Cuba', 'Located at the entrance of the Gulf of Mexico.'),
('geography', 'Capitals', 'What is the capital of Italy?', 'text', NULL, 'Rome', 'Known as the "Eternal City".'),
('geography', 'Deserts', 'The Gobi Desert is expanding.', 'boolean', NULL, 'True', 'Primarily due to climate change and overgrazing.'),
('sports', 'Soccer', 'Which club does Cristiano Ronaldo play for (as of 2023)?', 'multiple_choice', '["Manchester United", "Real Madrid", "Al-Nassr", "Juventus"]', 'Al-Nassr', 'He moved to the Saudi Arabian club in late 2022.'),
('sports', 'Basketball', 'How many NBA championships did Michael Jordan win?', 'multiple_choice', '["4", "5", "6", "7"]', '6', 'All with the Chicago Bulls.'),
('sports', 'Tennis', 'What is the surface of the French Open?', 'text', NULL, 'Clay', 'Known for being slow and producing high bounces.'),
('sports', 'Golf', 'What is the term for three strokes over par on a single hole?', 'text', NULL, 'Triple Bogey', 'A frustrating result for any golfer.'),
('sports', 'Baseball', 'How many players are on a standard MLB roster?', 'multiple_choice', '["24", "25", "26", "28"]', '26', 'Standard active roster size.'),
('sports', 'Boxing', 'Who was the first boxer to retire undefeated as heavyweight champion?', 'text', NULL, 'Rocky Marciano', 'Finished his career with a 49-0 record.'),
('sports', 'Olympics', 'The 2020 Summer Olympics were delayed until 2021.', 'boolean', NULL, 'True', 'Due to the COVID-19 pandemic.'),
('sports', 'Cycling', 'What color jersey does the points leader wear in the Tour de France?', 'multiple_choice', '["Yellow", "Green", "White", "Polka Dot"]', 'Green', 'Known as the "maillot vert".'),
('sports', 'Hockey', 'Which country has won the most Olympic gold medals in men''s ice hockey?', 'text', NULL, 'Canada', 'They have a long history of dominance in the sport.'),
('sports', 'American Football', 'Who is the all-time leading rusher in NFL history?', 'text', NULL, 'Emmitt Smith', 'He finished his career with 18,355 rushing yards.'),

('history', 'Space Race', 'What was the name of the NASA program that landed humans on the Moon?', 'text', NULL, 'Apollo', 'The program ran from 1961 to 1972.'),
('history', 'Ancient Egypt', 'Which Egyptian queen was known for her beauty and was the wife of Akhenaten?', 'text', NULL, 'Nefertiti', 'Her bust is one of the most copied works of ancient Egypt.'),
('history', 'American Civil War', 'The North was known as the Union.', 'boolean', NULL, 'True', 'The South was known as the Confederacy.'),
('history', 'Cold War', 'The "Red Scare" was a fear of which political ideology?', 'text', NULL, 'Communism', 'It was prominent in the US during the mid-20th century.'),
('history', 'French Revolution', 'Who was the radical leader of the Jacobins during the Reign of Terror?', 'text', NULL, 'Maximilien Robespierre', 'He was eventually executed by his own methods.'),
('history', 'Industrial Revolution', 'Which industry was the first to be industrialized?', 'multiple_choice', '["Agriculture", "Textiles", "Mining", "Transport"]', 'Textiles', 'The spinning jenny and power loom were key inventions.'),
('history', 'Ancient Greece', 'Sparta was known for its powerful military.', 'boolean', NULL, 'True', 'Spartan life was centered around loyalty to the state and military service.'),
('history', 'World War II', 'Who was the leader of Nazi Germany?', 'text', NULL, 'Adolf Hitler', 'His aggressive foreign policy triggered the war.'),
('history', 'Magna Carta', 'In which language was the Magna Carta originally written?', 'multiple_choice', '["English", "French", "Latin", "Greek"]', 'Latin', 'It was the standard language for legal documents in 1215.'),
('history', 'Ancient Rome', 'Who was the famous Roman general who was assassinated by his senators?', 'text', NULL, 'Julius Caesar', 'His death led to the end of the Roman Republic.'),
('science', 'Physics', 'What is the standard unit of temperature in science?', 'multiple_choice', '["Celsius", "Fahrenheit", "Kelvin", "Rankine"]', 'Kelvin', 'Based on absolute zero.'),
('science', 'Biology', 'Plants produce oxygen during photosynthesis.', 'boolean', NULL, 'True', 'Oxygen is a byproduct of the light-dependent reactions.'),
('science', 'Chemistry', 'What is the pH of a strong acid?', 'multiple_choice', '["1", "7", "10", "14"]', '1', 'The pH scale ranges from 0 to 14.'),
('science', 'Astronomy', 'Which is the fourth planet from the Sun?', 'text', NULL, 'Mars', 'Often called the "Red Planet".'),
('science', 'Geology', 'The Earth is estimated to be about 4.5 billion years old.', 'boolean', NULL, 'True', 'Based on radiometric dating of meteorite fragments.'),
('science', 'Mathematics', 'A circle has 360 degrees.', 'boolean', NULL, 'True', 'Standard measurement for a full rotation.'),
('science', 'Zoology', 'What is the largest species of shark?', 'text', NULL, 'Whale Shark', 'A slow-moving, filter-feeding carpet shark.'),
('science', 'Space', 'What was the first animal to orbit the Earth?', 'text', NULL, 'Laika', 'A Soviet space dog who flew on Sputnik 2 in 1957.'),
('science', 'Botany', 'The redwood tree is the tallest tree in the world.', 'boolean', NULL, 'True', 'Specifically the Coast Redwood.'),
('science', 'Chemistry', 'What is the chemical symbol for Nitrogen?', 'text', NULL, 'N', 'It is the most abundant gas in Earth''s atmosphere.'),
('pop-culture', 'Movies', 'What is the name of the fictional city in "The Lion King"?', 'text', NULL, 'Pride Rock', 'The home of Simba and his family.'),
('pop-culture', 'Music', 'Justin Bieber is from which country?', 'multiple_choice', '["USA", "UK", "Canada", "Australia"]', 'Canada', 'He was discovered on YouTube in 2008.'),
('pop-culture', 'TV Shows', 'Which show features a chemistry teacher making meth?', 'text', NULL, 'Breaking Bad', 'Starring Bryan Cranston as Walter White.'),
('pop-culture', 'Internet', 'What does "WWW" stand for?', 'text', NULL, 'World Wide Web', 'Invented by Tim Berners-Lee.'),
('pop-culture', 'Gaming', 'What is the name of the main character in "Pokémon"?', 'multiple_choice', '["Pikachu", "Ash Ketchum", "Gary Oak", "Professor Oak"]', 'Ash Ketchum', 'His goal is to become a Pokémon Master.'),
('pop-culture', 'Books', 'Who wrote "The Chronicles of Narnia"?', 'text', NULL, 'C.S. Lewis', 'A series of seven fantasy novels.'),
('pop-culture', 'Animation', 'Mickey Mouse was created by Walt Disney.', 'boolean', NULL, 'True', 'He first appeared in "Steamboat Willie" in 1928.'),
('pop-culture', 'Comics', 'Which superhero was born on the planet Krypton?', 'multiple_choice', '["Batman", "Superman", "Wonder Woman", "The Flash"]', 'Superman', 'His Kryptonian name is Kal-El.'),
('pop-culture', 'Streaming', 'Which platform produces "Stranger Things"?', 'text', NULL, 'Netflix', 'A flagship series for the service.'),
('pop-culture', 'Movies', 'Who played Rose in "Titanic"?', 'text', NULL, 'Kate Winslet', 'A role that launched her to global stardom.'),
('geography', 'Landmarks', 'Where is the Great Wall of China located?', 'text', NULL, 'China', 'Built to protect against invasions from the north.'),
('geography', 'Continents', 'Which is the only continent without a permanent human population?', 'multiple_choice', '["Africa", "Asia", "Antarctica", "Australia"]', 'Antarctica', 'Though it hosts many scientific research stations.'),
('geography', 'Cities', 'What is the capital of Canada?', 'text', NULL, 'Ottawa', 'Chosen as a compromise between Montreal and Toronto.'),
('geography', 'Oceans', 'Which ocean is the warmest?', 'multiple_choice', '["Pacific", "Atlantic", "Indian", "Arctic"]', 'Indian', 'Due to its location in the tropical region.'),
('geography', 'Mountains', 'What is the highest mountain in South America?', 'text', NULL, 'Aconcagua', 'Located in Argentina.'),
('geography', 'Rivers', 'The Danube is the longest river in Europe.', 'boolean', NULL, 'False', 'The Volga is the longest.'),
('geography', 'Countries', 'Which country is known as the "Land of the Midnight Sun"?', 'text', NULL, 'Norway', 'Parts of it are above the Arctic Circle.'),
('geography', 'Islands', 'Which is the largest island in the Mediterranean Sea?', 'multiple_choice', '["Sicily", "Sardinia", "Cyprus", "Crete"]', 'Sicily', 'An autonomous region of Italy.'),
('geography', 'Capitals', 'What is the capital of Brazil?', 'text', NULL, 'Brasilia', 'It was inaugurated in 1960 to move the capital inland.'),
('geography', 'Deserts', 'The Kalahari Desert is in Africa.', 'boolean', NULL, 'True', 'Covers much of Botswana and parts of Namibia and South Africa.'),
('sports', 'Soccer', 'Which player has won the most World Cups?', 'multiple_choice', '["Pelé", "Maradona", "Zidane", "Ronaldo"]', 'Pelé', 'He won three times (1958, 1962, 1970).'),
('sports', 'Basketball', 'How many periods are in an NBA game?', 'multiple_choice', '["2", "3", "4", "5"]', '4', 'Each quarter is 12 minutes long.'),
('sports', 'Tennis', 'What is a "deuce" in tennis?', 'text', NULL, 'A tie score of 40-40', 'Players must then win by two points.'),
('sports', 'Golf', 'What is the term for a score of one over par?', 'text', NULL, 'Bogey', 'A common score for amateur golfers.'),
('sports', 'Baseball', 'What is the "Seventh-Inning Stretch"?', 'text', NULL, 'A tradition of standing and stretching during the 7th inning', 'Usually accompanied by singing "Take Me Out to the Ball Game".'),
('sports', 'Boxing', 'Who was the first boxer to win a heavyweight title four times?', 'text', NULL, 'Evander Holyfield', 'Known as "The Real Deal".'),
('sports', 'Olympics', 'The Winter Olympics were first held in 1924.', 'boolean', NULL, 'True', 'The inaugural games were in Chamonix, France.'),
('sports', 'Cycling', 'What color is the "Polka Dot Jersey" in the Tour de France?', 'multiple_choice', '["Points leader", "King of the Mountains", "Best young rider", "Most aggressive"]', 'King of the Mountains', 'Awarded to the best climber.'),
('sports', 'Hockey', 'What is a "hat trick" in hockey?', 'text', NULL, 'Scoring three goals in a single game', 'Fans often throw hats onto the ice to celebrate.'),
('sports', 'American Football', 'How many points is a field goal worth?', 'text', NULL, '3', 'Kicked through the uprights.'),
('history', 'Ancient Greece', 'Who was the Greek god of war?', 'multiple_choice', '["Ares", "Zeus", "Apollo", "Hermes"]', 'Ares', 'Often depicted with a spear and helmet.'),
('history', 'American Revolution', 'The Boston Tea Party took place in which year?', 'text', NULL, '1773', 'A protest against the Tea Act.'),
('history', 'Ancient Egypt', 'The pharaoh Khufu is credited with building the Great Pyramid.', 'boolean', NULL, 'True', 'It was the tallest man-made structure for over 3,800 years.'),
('history', 'World War I', 'What was the name of the German airships used for bombing?', 'text', NULL, 'Zeppelins', 'Named after Count Ferdinand von Zeppelin.'),
('history', 'Medieval Europe', 'The Magna Carta was signed in 1215.', 'boolean', NULL, 'True', 'By King John of England at Runnymede.'),
('history', 'Civil Rights', 'Who was the leader of the Nation of Islam during the 1960s?', 'text', NULL, 'Elijah Muhammad', 'He was a mentor to Malcolm X.'),
('history', 'Viking Age', 'Vikings believed in a warrior''s afterlife called Valhalla.', 'boolean', NULL, 'True', 'Ruled over by the god Odin.'),
('history', 'Cold War', 'The Berlin Airlift was a response to a blockade by which country?', 'text', NULL, 'Soviet Union', 'The USSR blocked access to West Berlin in 1948.'),
('history', 'Ancient Rome', 'Who was the legendary first king of Rome?', 'text', NULL, 'Romulus', 'He and his brother Remus were said to be raised by a wolf.'),
('history', 'Space Race', 'What was the name of the first human-made object to reach the Moon''s surface?', 'text', NULL, 'Luna 2', 'Launched by the Soviet Union in 1959.'),
('science', 'Physics', 'What is the unit of power?', 'multiple_choice', '["Joule", "Watt", "Volt", "Ohm"]', 'Watt', 'Named after James Watt.'),
('science', 'Biology', 'The brain is part of the central nervous system.', 'boolean', NULL, 'True', 'Along with the spinal cord.'),
('science', 'Chemistry', 'What is the most reactive group of metals?', 'multiple_choice', '["Alkali metals", "Alkaline earth metals", "Transition metals", "Noble gases"]', 'Alkali metals', 'Group 1 elements like Lithium and Sodium.'),
('science', 'Astronomy', 'What is the name of the largest moon in the solar system?', 'text', NULL, 'Ganymede', 'One of Jupiter''s moons.'),
('science', 'Geology', 'What is the process of soil being moved by wind or water?', 'text', NULL, 'Erosion', 'A natural process that reshapes the landscape.'),
('science', 'Mathematics', 'A prime number has exactly two factors.', 'boolean', NULL, 'True', 'One and itself.'),
('science', 'Zoology', 'What is the smallest bird in the world?', 'text', NULL, 'Bee Hummingbird', 'Found primarily in Cuba.'),
('science', 'Space', 'The Great Red Spot is a giant storm on which planet?', 'text', NULL, 'Jupiter', 'It has been raging for at least 350 years.'),
('science', 'Botany', 'Plants breathe through small holes in their leaves called what?', 'text', NULL, 'Stomata', 'They allow for gas exchange.'),
('science', 'Chemistry', 'What is the chemical symbol for Helium?', 'text', NULL, 'He', 'A noble gas used in balloons.'),
('pop-culture', 'Movies', 'Who played Wolverine in the X-Men films?', 'multiple_choice', '["Hugh Jackman", "Patrick Stewart", "Ian McKellen", "James Marsden"]', 'Hugh Jackman', 'He played the role for 17 years.'),
('pop-culture', 'Music', 'Michael Jackson released the album "Thriller".', 'boolean', NULL, 'True', 'The best-selling album of all time.'),
('pop-culture', 'TV Shows', 'What is the name of the family in "The Simpsons"?', 'text', NULL, 'Simpsons', 'Homer, Marge, Bart, Lisa, and Maggie.'),
('pop-culture', 'Internet', 'Who co-founded Google?', 'multiple_choice', '["Larry Page & Sergey Brin", "Bill Gates & Paul Allen", "Steve Jobs & Steve Wozniak", "Mark Zuckerberg"]', 'Larry Page & Sergey Brin', 'Founded in a garage in 1998.'),
('pop-culture', 'Gaming', 'What is the name of the hero in "The Legend of Zelda"?', 'text', NULL, 'Link', 'Zelda is actually the princess.'),
('pop-culture', 'Books', 'Who wrote "Pride and Prejudice"?', 'text', NULL, 'Jane Austen', 'Published in 1813.'),
('pop-culture', 'Animation', 'The Lion King is based on "Hamlet".', 'boolean', NULL, 'True', 'A young prince seeks revenge for his father''s death.'),
('pop-culture', 'Comics', 'What is the real name of Wonder Woman?', 'text', NULL, 'Diana Prince', 'A princess of the Amazons.'),
('pop-culture', 'Streaming', 'Which platform produces "The Crown"?', 'text', NULL, 'Netflix', 'A historical drama about the reign of Queen Elizabeth II.'),
('pop-culture', 'Movies', 'Who directed "The Godfather"?', 'multiple_choice', '["Scorsese", "Coppola", "Spielberg", "Tarantino"]', 'Francis Ford Coppola', 'Widely regarded as one of the greatest films.'),
('geography', 'Landmarks', 'Where is the Parthenon located?', 'text', NULL, 'Athens', 'Dedicated to the goddess Athena.'),
('geography', 'Continents', 'Asia is the largest continent by population.', 'boolean', NULL, 'True', 'Home to over 4.5 billion people.'),
('geography', 'Cities', 'What is the capital of China?', 'text', NULL, 'Beijing', 'A major political and cultural hub.'),
('geography', 'Oceans', 'Which ocean is the shallowest?', 'multiple_choice', '["Pacific", "Atlantic", "Indian", "Arctic"]', 'Arctic', 'Much smaller than the other oceans.'),
('geography', 'Mountains', 'The Andes are the longest continental mountain range.', 'boolean', NULL, 'True', 'Located in South America.'),
('geography', 'Rivers', 'Which river is known as the "Mother River of China"?', 'text', NULL, 'Yellow River', 'Also known as the Huang He.'),
('geography', 'Countries', 'Which country is known as the "Land of the Rising Sun"?', 'text', NULL, 'Japan', 'A translation of the name Nippon.'),
('geography', 'Islands', 'Which island is the largest in the world?', 'text', NULL, 'Greenland', 'An autonomous territory of Denmark.'),
('geography', 'Capitals', 'What is the capital of Egypt?', 'text', NULL, 'Cairo', 'The largest city in the Arab world.'),
('geography', 'Deserts', 'The Atacama Desert is in which continent?', 'text', NULL, 'South America', 'Located in Chile.'),
('sports', 'Soccer', 'Which club has won the most English Premier League titles?', 'multiple_choice', '["Arsenal", "Chelsea", "Liverpool", "Manchester United"]', 'Manchester United', 'They have 13 titles.'),
('sports', 'Basketball', 'The "Bulls" are a basketball team from which city?', 'text', NULL, 'Chicago', 'Made famous by Michael Jordan.'),
('sports', 'Tennis', 'What is a "Grand Slam" in professional tennis?', 'text', NULL, 'Winning all 4 major titles in a single year', 'Australian Open, French Open, Wimbledon, US Open.'),
('sports', 'Golf', 'What is the term for two strokes under par on a single hole?', 'text', NULL, 'Eagle', 'A great score for any golfer.'),
('sports', 'Baseball', 'What is the name of the Boston MLB team?', 'multiple_choice', '["Yankees", "Cubs", "Red Sox", "Dodgers"]', 'Red Sox', 'Known for the "Green Monster" at Fenway Park.'),
('sports', 'Boxing', 'Who was the first boxer to win the heavyweight title from Muhammad Ali?', 'text', NULL, 'Joe Frazier', 'In the "Fight of the Century" in 1971.'),
('sports', 'Olympics', 'The 2028 Summer Olympics will be held in which city?', 'multiple_choice', '["Paris", "Los Angeles", "Tokyo", "London"]', 'Los Angeles', 'The city will host for the third time.'),
('sports', 'Cycling', 'The Tour de France is a race for which type of vehicle?', 'text', NULL, 'Bicycle', 'An annual multi-stage bicycle race.'),
('sports', 'Hockey', 'What is the term for a puck being hit into the net?', 'text', NULL, 'Goal', 'The primary way to score in hockey.'),
('sports', 'American Football', 'Who is the all-time leader in touchdown passes in the NFL?', 'text', NULL, 'Tom Brady', 'He finished his career with 649 touchdown passes.'),
('history', 'Ancient Rome', 'The Roman Empire reached its greatest extent under which emperor?', 'multiple_choice', '["Augustus", "Trajan", "Hadrian", "Marcus Aurelius"]', 'Trajan', 'In 117 AD, the empire spanned from Britain to the Persian Gulf.'),
('history', 'American Revolution', 'Who was the first person to sign the Declaration of Independence?', 'text', NULL, 'John Hancock', 'He signed with a large, stylish signature.'),
('history', 'Ancient Egypt', 'The Valley of the Kings is located on the west bank of the Nile.', 'boolean', NULL, 'True', 'Across from the ancient city of Thebes.'),
('history', 'World War II', 'What was the name of the German secret code broken by Alan Turing?', 'text', NULL, 'Enigma', 'Turing and his team at Bletchley Park developed the Bombe to crack it.'),
('history', 'Cold War', 'The SALT treaties were between the US and which country?', 'text', NULL, 'Soviet Union', 'SALT stands for Strategic Arms Limitation Talks.'),
('history', 'Renaissance', 'Who is famous for painting the ceiling of the Sistine Chapel?', 'text', NULL, 'Michelangelo', 'The work took four years to complete (1508-1512).'),
('history', 'Viking Age', 'Which Viking explorer is credited with discovering Greenland?', 'text', NULL, 'Erik the Red', 'He founded the first Norse settlement there in 982.'),
('history', 'Civil Rights', 'In which city did the Selma to Montgomery marches take place?', 'text', NULL, 'Selma', 'The marches were a pivotal moment in the movement.'),
('history', 'Ancient Greece', 'The Olympics were held in honor of which god?', 'text', NULL, 'Zeus', 'Held every four years in Olympia.'),
('history', 'Medieval Europe', 'The Hundred Years'' War was fought between England and which country?', 'text', NULL, 'France', 'It actually lasted 116 years (1337-1453).'),
('science', 'Physics', 'What is the absolute zero temperature in Celsius?', 'text', NULL, '-273.15', 'The point at which all molecular motion stops.'),
('science', 'Biology', 'Cells are the basic unit of life.', 'boolean', NULL, 'True', 'The cell theory states that all living things are made of cells.'),
('science', 'Chemistry', 'What is the only metal that is liquid at room temperature?', 'text', NULL, 'Mercury', 'Also known as quicksilver.'),
('science', 'Astronomy', 'What is the name of the large asteroid belt between Mars and Jupiter?', 'text', NULL, 'Asteroid Belt', 'Contains millions of rocky bodies.'),
('science', 'Geology', 'The Earth''s crust is divided into large pieces called what?', 'text', NULL, 'Tectonic Plates', 'Their movement causes earthquakes and volcanoes.'),
('science', 'Mathematics', 'A polygon with eight sides is called an octagon.', 'boolean', NULL, 'True', 'A stop sign is a common example.'),
('science', 'Zoology', 'What is the largest species of great ape?', 'text', NULL, 'Eastern Gorilla', 'Found in the mountains of Central Africa.'),
('science', 'Space', 'The sun is a star.', 'boolean', NULL, 'True', 'A yellow dwarf star at the center of our solar system.'),
('science', 'Botany', 'What is the study of fungi called?', 'text', NULL, 'Mycology', 'Fungi are distinct from plants as they cannot photosynthesize.'),
('science', 'Chemistry', 'What is the chemical symbol for Carbon?', 'text', NULL, 'C', 'The basis of all known life on Earth.'),
('pop-culture', 'Movies', 'Who played Iron Man in the Marvel Cinematic Universe?', 'text', NULL, 'Robert Downey Jr.', 'He started the franchise in 2008.'),
('pop-culture', 'Music', 'The album "Dark Side of the Moon" is by which band?', 'text', NULL, 'Pink Floyd', 'One of the most critically acclaimed albums.'),
('pop-culture', 'TV Shows', '"The Sopranos" is about a mob boss in which US state?', 'text', NULL, 'New Jersey', 'Starring James Gandolfini as Tony Soprano.'),
('pop-culture', 'Internet', 'Which platform is known for short-form video content and viral trends?', 'text', NULL, 'TikTok', 'Owned by ByteDance.'),
('pop-culture', 'Gaming', 'What is the name of the main antagonist in the "Legend of Zelda" series?', 'text', NULL, 'Ganon', 'Also known as Ganondorf.'),
('pop-culture', 'Books', 'Who wrote "The Hobbit"?', 'text', NULL, 'J.R.R. Tolkien', 'A prelude to The Lord of the Rings.'),
('pop-culture', 'Animation', 'Woody and Buzz Lightyear are characters in which movie?', 'text', NULL, 'Toy Story', 'The first Pixar feature film.'),
('pop-culture', 'Comics', 'What is the real name of the Flash?', 'text', NULL, 'Barry Allen', 'A forensic scientist for the Central City Police.'),
('pop-culture', 'Streaming', 'Which service produced the hit series "Ted Lasso"?', 'text', NULL, 'Apple TV+', 'A comedy-drama about an American football coach.'),
('pop-culture', 'Movies', 'Who directed "Avatar"?', 'text', NULL, 'James Cameron', 'It became the highest-grossing film of all time.'),
('geography', 'Landmarks', 'In which city is the Big Ben clock tower located?', 'text', NULL, 'London', 'Part of the Palace of Westminster.'),
('geography', 'Continents', 'South America is home to the world''s largest rainforest.', 'boolean', NULL, 'True', 'The Amazon Rainforest.'),
('geography', 'Cities', 'What is the capital of Germany?', 'text', NULL, 'Berlin', 'A city known for its history and culture.'),
('geography', 'Oceans', 'Which ocean is the smallest?', 'text', NULL, 'Arctic Ocean', 'Much smaller than the others.'),
('geography', 'Mountains', 'What is the name of the mountain range that separates Europe and Asia?', 'text', NULL, 'Ural Mountains', 'Located primarily in Russia.'),
('geography', 'Rivers', 'The Mississippi River flows into which body of water?', 'text', NULL, 'Gulf of Mexico', 'The largest gulf in the world.'),
('geography', 'Countries', 'Which country has the most volcanoes?', 'text', NULL, 'Indonesia', 'Located on the Pacific Ring of Fire.'),
('geography', 'Islands', 'Which island is a state of Australia?', 'text', NULL, 'Tasmania', 'Located south of the mainland.'),
('geography', 'Capitals', 'What is the capital of China?', 'text', NULL, 'Beijing', 'A major political and cultural center.'),
('geography', 'Deserts', 'The Mojave Desert is located in which country?', 'text', NULL, 'USA', 'Located primarily in California and Nevada.'),
('sports', 'Soccer', 'Which country has won the most FIFA World Cups in women''s soccer?', 'text', NULL, 'USA', 'The USWNT has won four titles.'),
('sports', 'Basketball', 'The "Lakers" are from which city?', 'text', NULL, 'Los Angeles', 'One of the most successful NBA franchises.'),
('sports', 'Tennis', 'What is the nickname for the Wimbledon tournament?', 'text', NULL, 'The Championships', 'The world''s oldest tennis tournament.'),
('sports', 'Golf', 'What is the term for a score of two over par on a single hole?', 'text', NULL, 'Double Bogey', 'A common score in recreational golf.'),
('sports', 'Baseball', 'What is the name of the Chicago MLB team known as the "South Siders"?', 'text', NULL, 'White Sox', 'Playing at Guaranteed Rate Field.'),
('sports', 'Boxing', 'Who was known as "Iron Mike"?', 'text', NULL, 'Mike Tyson', 'A dominant heavyweight champion in the 80s and 90s.'),
('sports', 'Olympics', 'The Olympic Games are held every two years (alternating Summer and Winter).', 'boolean', NULL, 'True', 'Each occurs on a four-year cycle.'),
('sports', 'Cycling', 'What is the name of the multi-stage cycling race in Italy?', 'text', NULL, 'Giro d''Italia', 'One of the three Grand Tours.'),
('sports', 'Hockey', 'What is the name of the penalty where a player is sent off for 2 minutes?', 'text', NULL, 'Minor Penalty', 'The most common type of penalty.'),
('sports', 'American Football', 'Who is known as "The GOAT" of NFL quarterbacks?', 'text', NULL, 'Tom Brady', 'Winner of 7 Super Bowls.');
